CREATE DATABASE IF NOT EXISTS prototipo_zoom;
USE prototipo_zoom;

CREATE TABLE Usuarios (
    IdUsuario INT AUTO_INCREMENT PRIMARY KEY,
    Nombres VARCHAR(120) NOT NULL,
    Correo VARCHAR(150) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    Rol VARCHAR(20) NOT NULL DEFAULT 'Usuario',
    Activo TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE Salas (
    IdSala INT AUTO_INCREMENT PRIMARY KEY,
    CodigoSala VARCHAR(20) NOT NULL UNIQUE,
    Nombre VARCHAR(120) NOT NULL,
    IdHost INT NOT NULL,
    Estado VARCHAR(20) NOT NULL DEFAULT 'Activa',
    FechaCreacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdHost) REFERENCES Usuarios(IdUsuario) ON DELETE CASCADE
);


CREATE TABLE ParticipantesSala (
    IdParticipante INT AUTO_INCREMENT PRIMARY KEY,
    IdSala INT NOT NULL,
    IdUsuario INT NOT NULL,
    Estado VARCHAR(20) NOT NULL, -- 'Aceptado', 'Retirado'
    FechaIngreso DATETIME NULL,
    FOREIGN KEY (IdSala) REFERENCES Salas(IdSala) ON DELETE CASCADE,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(IdUsuario) ON DELETE CASCADE
);


CREATE TABLE SolicitudesSala (
    IdSolicitud INT AUTO_INCREMENT PRIMARY KEY,
    IdSala INT NOT NULL,
    IdUsuario INT NOT NULL,
    Estado VARCHAR(20) NOT NULL DEFAULT 'Pendiente', -- 'Pendiente', 'Aceptado', 'Rechazado'
    FechaSolicitud DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdSala) REFERENCES Salas(IdSala) ON DELETE CASCADE,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(IdUsuario) ON DELETE CASCADE
);


CREATE TABLE Mensajes (
    IdMensaje INT AUTO_INCREMENT PRIMARY KEY,
    IdSala INT NOT NULL,
    IdUsuario INT NOT NULL,
    Contenido TEXT NOT NULL,
    FechaEnvio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdSala) REFERENCES Salas(IdSala) ON DELETE CASCADE,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(IdUsuario) ON DELETE CASCADE
);


CREATE TABLE ArchivosCompartidos (
    IdArchivo INT AUTO_INCREMENT PRIMARY KEY,
    IdSala INT NOT NULL,
    IdUsuario INT NOT NULL,
    NombreArchivo VARCHAR(255) NOT NULL,
    RutaArchivo VARCHAR(500) NOT NULL,
    TamanioBytes BIGINT NOT NULL,
    Extension VARCHAR(10) NOT NULL,
    FechaEnvio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (IdSala) REFERENCES Salas(IdSala) ON DELETE CASCADE,
    FOREIGN KEY (IdUsuario) REFERENCES Usuarios(IdUsuario) ON DELETE CASCADE
);